### ISSUE TITLE
Wifi and interrupts

### ISSUE THREAD

**Issue by frollard** [elipsitz/internet-connected-pinball#1]
Before replicating this version I had one question: The rp pico w documentation suggests that the IRQ capabilities will be hampered while the WIFI is in use...are you finding that you can transmit while the pio loop is listening to the bus? 
https://datasheets.raspberrypi.com/picow/pico-w-datasheet.pdf page 19 regarding spi bus (to wifi module) and the IRQ. In theory from the rp2040 block diagram the pio should be in a league of its own and the irq only applies to the main processor.

We intend to do the same...Our current setup does similar by making a physical shadow copy of the ram, and only doing reads from the shadow copy to prevent a game breaking collision; at worst we corrupt the shadow causing a shadow write miss. Then with our live copy of the data (that we shouldn't read from super often) We combine the scores with an rfid user system that keeps a high score list on the server...I'd like to try your route of using the pico as shadow, and then having the 2nd core handle fun stuff like live commentating the game events to a chat room, controlling other peripherals, etc.
In a flip universe I could see totally emulating the game ram in-situ, such that we could change the machine adjusts/game state live (tap rfid card to build a custom deterministic tournament mode, etc). Much easier to man-in-the-middle the ram if you ARE the ram ;)

**Comment by elipsitz** [comment]
I have the pio loop continuously running, and haven't found there to be any issues with WiFi, so I don't think this is a problem.

Reading the datasheet, I believe that line is only talking the IRQ from the wifi chip that's multiplexed over the same pin as spi data in/out, which doesn't affect anything else on the system. All of that communication is all handled by the Pico SDK anyway.
